[package]
name = "assembler_web"
version = "0.1.0"
edition = "2021"

[dependencies]
assembler = { package = "arshu-assembler", path = "../Assembler" }
arshu = { path = "../Arshu" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
actix-web = "4.0"
actix-files = "0.6"
utoipa = "4"
utoipa-scalar = { version = "0.3", features = ["actix-web"] }
webbrowser = "0.8"
futures-util = "0.3"
reqwest = "0.11"
chrono = "0.4"
uuid = { version = "1.0", features = ["v4"] }
regex = "1.0"
